//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyInEveryHome.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int IDContract { get; set; }
        public int NumberAccount { get; set; }
        public int IDUser { get; set; }
        public int Amount { get; set; }
        public string Period { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.TimeSpan Percet { get; set; }
    
        public virtual User User { get; set; }
    }
}
