//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyInEveryHome.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IDOperation { get; set; }
        public string NameOperation { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Amount { get; set; }
        public int Account { get; set; }
    
        public virtual BackAccount BackAccount { get; set; }
    }
}
